base:
 random_state: 42
 split_size : 0.2
 cv : 5
 target : "treatment"
 verbose : 0
 n_jobs : -1

baseline_models:
  LogisticRegression:
    solver: liblinear
    max_iter: 200
    random_state: 42

  RandomForestClassifier:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    random_state: 42

  XGBClassifier:
    use_label_encoder: false
    eval_metric: logloss
    n_estimators: 100
    max_depth: 3
    learning_rate: 0.1
    subsample: 0.8
    random_state: 42

  LGBMClassifier:
    n_estimators: 100
    max_depth: -1
    learning_rate: 0.1
    random_state: 42

  CatBoostClassifier:
    iterations: 100
    depth: 3
    learning_rate: 0.1
    random_state: 42
    verbose: 0